### ISSUE TITLE
Prevent worker download and update container automatically unless a flag is set!!!

### ISSUE THREAD

**Issue by para1131** [nebula-orchestrator/manager#71]
## Expected/Wanted Behavior
Hi Guys,

Problem:
I need to give the possibility to worker that when the update from nebula manager is released,  worker check a flag and if the flag is set then fetch and replace the new version of container on the device, Else do not update the new version unless the worker receive a trigger or the flag is set.

Questions?
1- I really don't know where should I start. is there such capability now in worker?
should I manipulate worker.py in worker container based on my need?

2- if I done question.  how do I make the iot devices to install the new worker? i mean how should I create new worker with edited worker.py.

**Comment by naorlivne** [comment]
Hi @para1131 

I'm not sure I understand what your asking for or your use case, Generally you only send the API update command from the manager when you want a new version to update or to change envvars\etc (which requires a container to be replaced too), can you explain what you had in mind & why you need to have an option to have an update set but not have it update a worker?

**Comment by para1131** [comment]
> Hi @para1131
> 
> I'm not sure I understand what your asking for or your use case, Generally you only send the API update command from the manager when you want a new version to update or to change envvars\etc (which requires a container to be replaced too), can you explain what you had in mind & why you need to have an option to have an update set but not have it update a worker?

Thats right after sending the update command from manager all iot device would be updated automatically after its corresponding worker see the latest update. 

After the release of new version by Manager I want to worker notify user through mobile APP or  another app that there is a new version should I update the container or not? actually it let the user to choose if his device should be updated automatically or not, a kind of interaction between user and worker. he should decide if the Iot device use the older version or the new one(specifically because of data usage).

**Comment by naorlivne** [comment]
> > Hi @para1131
> > I'm not sure I understand what your asking for or your use case, Generally you only send the API update command from the manager when you want a new version to update or to change envvars\etc (which requires a container to be replaced too), can you explain what you had in mind & why you need to have an option to have an update set but not have it update a worker?
> 
> Thats right after sending the update command from manager all iot device would be updated automatically after its corresponding worker see the latest update.
> 
> After the release of new version by Manager I want to worker notify user through mobile APP or another app that there is a new version should I update the container or not? actually it let the user to choose if his device should be updated automatically or not, a kind of interaction between user and worker. he should decide if the Iot device use the older version or the new one(specifically because of data usage).

Thanks for clearing it up.

This option is not something supported in Nebula out of the box (nor it will be something I will add to the core Nebula functionality) but that been said there are 2 ways I think you can go about attacking that request:

1. You use the mobile app to send the update request to the API & use the CI/CD  to notify the user via the APP push request\etc
2. You fork Nebula & modify to fit your need (it's open source for reason like this) - You'll likely need to modify the worker.py & build a new container for that, you can look at https://github.com/nebula-orchestrator/worker/blob/master/CONTRIBUTING for a bit more info about it but it's noting more complex then building a new docker version of the worker Dockerfile and using that on your workers rather then the offical worker containers

**Comment by para1131** [comment]
>     2\. to modify the worker.py & build a new container for tha

Thanks @naorlivne , ja, I have to get my feet wet.

**Comment by naorlivne** [comment]
Closing as the question seemed answered & it's not something that will require additional work on Nebula project side.
